# Generated by Django 2.2.5 on 2021-04-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20210417_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amentities',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='reservations.Amentity'),
        ),
    ]
