# Generated by Django 2.2.5 on 2021-05-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210417_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='amentities',
        ),
        migrations.DeleteModel(
            name='Amentity',
        ),
    ]
